name: Build (Linux + Windows)

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gperf \
          automake \
          autoconf \
          autoconf-archive \
          libtool \
          libltdl-dev \
          pkg-config \
          flex \
          bison \
          m4 \
          gettext \
          ninja-build


    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies via vcpkg
      run: |
        ./vcpkg/vcpkg install sdl3:x64-linux eigen3:x64-linux

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build (Linux)
      run: cmake --build build --config Release

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies via vcpkg
      run: |
        .\vcpkg\vcpkg.exe install sdl3:x64-windows eigen3:x64-windows

    - name: Configure CMake
      shell: bash
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows

    - name: Build (Windows)
      shell: bash
      run: cmake --build build --config Release
